name: Build QMI Packages for BPI-R4

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gettext libncurses-dev libssl-dev python3 zstd rsync unzip file wget

    - name: Download and Extract OpenWrt SDK
      run: |
        wget https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
        tar --use-compress-program=unzstd -xf openwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
        SDK_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-mediatek-filogic*" | head -n1)
        mv "$SDK_DIR" sdk

    - name: Build QMI Packages
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install uqmi luci-proto-qmi

        make defconfig
        make package/network/utils/uqmi/compile -j$(nproc) V=s
        make package/network/utils/comgt/compile -j$(nproc) V=s
        make package/network/utils/modemmanager/compile -j$(nproc) V=s
        make package/network/services/luci-proto-qmi/compile -j$(nproc) V=s

    - name: Upload Built IPK Packages
      uses: actions/upload-artifact@v4
      with:
        name: qmi-ipks
        path: |
          sdk/bin/packages/*/*/*.ipk
