name: Build QMI Packages for BPI-R4

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk \
          gettext libncurses-dev libssl-dev rsync \
          unzip zlib1g-dev file wget python3-pip
        pip install gdown

    - name: Download MP4.0 SDK from Google Drive
      run: |
        gdown 1U0tnvoaxDujO1q5QNxnw0i2d93X2zi9r -O sdk.zip
        unzip sdk.zip
        mv BPI-R4-BE1350-WIFI_MP4_0-SDK-20240620 sdk

    - name: Build selected packages
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/network/utils/uqmi/compile -j2 V=s
        make package/kernel/linux/compile -j2 V=s
        make package/network/utils/comgt/compile -j2 V=s
        make package/network/utils/usb-modeswitch/compile -j2 V=s
        make package/network/utils/wwan/compile -j2 V=s
        make package/network/utils/luci-proto-qmi/compile -j2 V=s

    - name: Upload built packages
      uses: actions/upload-artifact@v4
      with:
        name: ipk-packages
        path: |
          sdk/bin/packages/aarch64_cortex-a53/base/*.ipk
